/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Connected, authenticated client over TLS 1.3 + SCRAM-Argon2id. */
export declare class ShamirClient {
  /**
   * Run the full TCP→TLS→SCRAM handshake; resolves to a connected
   * client.
   */
  static connect(opts: ConnectOptions): Promise<ShamirClient>
  /**
   * `SHA256(server_ed25519_pub_key)` — persist this and pass back
   * as `trustedPin` on subsequent connections.
   */
  serverPubKeyPin(): Buffer
  /** 32-byte session id assigned by the server. */
  sessionId(): Buffer
  /**
   * Absolute session expiry (unix nanoseconds). Returned as `BigInt`
   * in JS because nanoseconds since epoch overflow `Number`.
   */
  expiresAtNs(): bigint
  /** Resumption ticket bytes (if the server issued one). */
  resumptionTicket(): Buffer | null
  /** Resumption expiry (paired with [`Self::resumption_ticket`]). */
  resumptionExpiresAtNs(): bigint | null
  /** Health check. */
  ping(): Promise<void>
  /**
   * Execute a `BatchRequest` (passed as a MessagePack-encoded `Buffer`)
   * against the named database. Returns the full `BatchResponse` as a
   * MessagePack-encoded `Buffer`.
   */
  execute(db: string, batch: Buffer): Promise<Buffer>
  /**
   * Privileged replication pull-API (REPLICATION §5). Takes a msgpack
   * `ReplRequest` Buffer, returns a msgpack `ReplResponse` Buffer. The
   * session must hold the `replicator` role (or be superuser).
   */
  repl(req: Buffer): Promise<Buffer>
  /**
   * Create a new SCRAM-authenticatable user. Requires the current
   * session to belong to a superuser. Returns the stable 16-byte
   * `user_id` as a Buffer.
   */
  createScramUser(name: string, password: string, roles: Array<string>): Promise<Buffer>
  /**
   * Close the TLS write half cleanly. Idempotent — second call is
   * a no-op.
   */
  close(): Promise<void>
}

/** Connection parameters passed to `ShamirClient.connect`. */
export interface ConnectOptions {
  /** Server host (e.g. `"127.0.0.1"` or `"db.example.com"`). */
  host: string
  /** Server port. */
  port: number
  /** SNI hostname for TLS — usually matches the cert's CN. */
  serverName: string
  /** Username (raw — server-side normalisation applies). */
  username: string
  /**
   * Plaintext password. Zeroised in the native side after the
   * handshake completes.
   */
  password: string
  /**
   * Trust-on-first-use: accept whatever Ed25519 pubkey the server
   * presents on first connection. `true` for first connect; once you
   * persist the pin, switch to `false` and pass `trustedPin`.
   */
  acceptNewHost?: boolean
  /**
   * Pre-pinned `SHA256(server_ed25519_pub_key)` — 32 bytes. When
   * supplied, mismatch fails the handshake.
   */
  trustedPin?: Buffer
}
