// Typed-error wrapper for the shamir-client native binding.
//
// `index.js` is auto-generated by napi-rs (`napi build`) and exports only
// the raw `ShamirClient` class whose `execute` / `repl` / `createScramUser`
// methods take and return raw MessagePack `Buffer`s. This wrapper is the
// package's real entry point (`package.json` → `main`): it enriches the
// native class with:
//
//   1. **ShamirDbError** — a typed Error subclass mirroring the TS SDK's
//      `ShamirDbError` (`shamir-client-ts/src/core/errors.ts`), carrying
//      `.code` and `.retryable`.
//   2. **execute** — accepts a plain JS object, returns a plain JS object
//      (msgpack encode/decode happens here, as before).
//   3. **repl / createScramUser** — detect domain-level DB error markers
//      and throw `ShamirDbError`.
//
// **Why a JS-side wrapper (task #519):** napi-rs 3.x async `#[napi]` fns
// hard-pin the error type to `napi::Error<Status>`, so a structured error
// with `.code` cannot be thrown from Rust. Instead, the Rust side returns
// `Ok(Buffer)` containing a msgpack `DbResponse::Error { kind: "error",
// code, message }`. This wrapper decodes the buffer and, if the marker is
// present, throws `ShamirDbError`.

'use strict';

const { encode, decode } = require('@msgpack/msgpack');
const native = require('./index.js');

// ---------------------------------------------------------------------------
// ShamirDbError — mirrors the TS SDK's ShamirDbError
// (shamir-client-ts/src/core/errors.ts).
// ---------------------------------------------------------------------------

/**
 * Server error codes that are transient — the same request may succeed on a
 * retry (possibly after a backoff, or against the leader for
 * `read_only_replica`).
 */
const RETRYABLE_ERROR_CODES = new Set([
  'timeout',
  'lock_timeout',
  'tx_conflict',
  'read_only_replica',
]);

/** `true` if `code` is a transient failure worth retrying. */
function isRetryableCode(code) {
  return RETRYABLE_ERROR_CODES.has(code);
}

/**
 * A typed DB-layer error carrying the server's `code` and a `retryable`
 * classification. Thrown in place of a plain `Error` for every
 * `DbResponse::Error` the server returns from `execute`, `repl`, or
 * `createScramUser`.
 *
 * `message` keeps the human-readable `db error [code]: message` form for
 * logging continuity, but callers should branch on `.code` / `.retryable`.
 */
class ShamirDbError extends Error {
  constructor(code, detail) {
    super(`db error [${code}]: ${detail}`);
    this.name = 'ShamirDbError';
    this.code = code;
    this.detail = detail;
    this.retryable = isRetryableCode(code);
  }
}

// ---------------------------------------------------------------------------
// Internal: decode a response Buffer, throwing ShamirDbError if it carries a
// DbResponse::Error marker.
//
// The native side encodes domain DB errors as
// `{ kind: "error", code: "...", message: "..." }`. Normal success payloads
// never carry `kind: "error"` (BatchResponse is a plain struct with no `kind`
// field; ReplResponse uses `repl_kind`; raw user-id bytes don't decode to a
// map with that key).
// ---------------------------------------------------------------------------

function decodeOrThrow(buf) {
  const decoded = decode(new Uint8Array(buf));
  if (decoded && decoded.kind === 'error') {
    throw new ShamirDbError(decoded.code, decoded.message);
  }
  return decoded;
}

// ---------------------------------------------------------------------------
// Wrapped ShamirClient.
// ---------------------------------------------------------------------------

class ShamirClient extends native.ShamirClient {
  /**
   * Execute a BatchRequest (plain JS object) and return the BatchResponse
   * as a plain JS object. Throws ShamirDbError on domain-level DB errors.
   */
  async execute(db, batchObj) {
    const buf = Buffer.from(encode(batchObj));
    const resp = await super.execute(db, buf);
    return decodeOrThrow(resp);
  }

  /**
   * Replication pull-API. Takes/returns raw msgpack Buffers (the caller
   * handles encoding/decoding). Throws ShamirDbError on domain-level DB
   * errors.
   */
  async repl(req) {
    const resp = await super.repl(req);
    try {
      decodeOrThrow(resp);
    } catch (e) {
      if (e instanceof ShamirDbError) throw e;
    }
    return resp;
  }

  /**
   * Create a SCRAM user. Returns the 16-byte user_id Buffer.
   * Throws ShamirDbError on domain-level DB errors (e.g. "user_exists").
   */
  async createScramUser(name, password, roles) {
    const resp = await super.createScramUser(name, password, roles);
    try {
      decodeOrThrow(resp);
    } catch (e) {
      if (e instanceof ShamirDbError) throw e;
    }
    return resp;
  }
}

module.exports = {
  ...native,
  ShamirClient,
  ShamirDbError,
  isRetryableCode,
  RETRYABLE_ERROR_CODES,
};
