/**
 * ShamirDB Node.js client SDK — typed-error surface.
 *
 * This is the package entry point (`package.json` → `main`). The raw native
 * binding is in `index.js` (auto-generated by napi-rs); this wrapper adds
 * ShamirDbError and object-level execute/repl/createScramUser.
 */

/**
 * Server error codes that are transient — the same request may succeed on a
 * retry.
 */
export declare const RETRYABLE_ERROR_CODES: ReadonlySet<string>;

/** `true` if `code` is a transient failure worth retrying. */
export declare function isRetryableCode(code: string): boolean;

/**
 * A typed DB-layer error carrying the server's `code` and a `retryable`
 * classification. Thrown for every `DbResponse::Error` the server returns
 * from `execute`, `repl`, or `createScramUser`.
 *
 * Mirrors the TS SDK's `ShamirDbError` (`shamir-client-ts/src/core/errors.ts`).
 */
export declare class ShamirDbError extends Error {
  /** Server error code (e.g. "timeout", "validation", "tx_conflict"). */
  readonly code: string;
  /** Human-readable detail returned by the server (without the code prefix). */
  readonly detail: string;
  /** Whether retrying the same request may succeed. */
  readonly retryable: boolean;
}

/** Connection parameters. */
export interface ConnectOptions {
  host: string;
  port: number;
  serverName: string;
  username: string;
  password: string;
  acceptNewHost?: boolean;
  trustedPin?: Buffer;
}

/**
 * A connected, authenticated client. `execute` accepts a plain JS object and
 * returns a plain JS object (msgpack encode/decode is handled internally).
 */
export declare class ShamirClient {
  static connect(opts: ConnectOptions): Promise<ShamirClient>;
  serverPubKeyPin(): Buffer;
  sessionId(): Buffer;
  expiresAtNs(): bigint;
  resumptionTicket(): Buffer | null;
  resumptionExpiresAtNs(): bigint | null;
  ping(): Promise<void>;
  /** Execute a BatchRequest (plain JS object). Returns BatchResponse as a JS object. */
  execute(db: string, batch: object): Promise<object>;
  repl(req: Buffer): Promise<Buffer>;
  createScramUser(name: string, password: string, roles: string[]): Promise<Buffer>;
  close(): Promise<void>;
}
