/**
 * Cross-language msgpack byte-parity test — TS client vs Rust fixture.
 *
 * Proves the TS client (`@msgpack/msgpack` v3 `encode`) and the Rust client
 * (`rmp_serde::to_vec_named`) emit BYTE-IDENTICAL msgpack for the 10 canonical
 * replication-DDL `BatchOp` variants.
 *
 * The authoritative wire contract is the Rust fixture
 * `crates/shamir-query-builder/tests/fixtures/repl_ddl_msgpack.json`
 * (commit b0d427f8), regenerated by `tests/repl_ddl_msgpack.rs` in
 * `shamir-query-builder`. The Rust-side inputs that produced the fixture are
 * the literals in `canonical_ops()` in that test file; this test mirrors those
 * EXACT inputs (same strings, same nesting) through the TS builders.
 *
 * Key-order invariant: `@msgpack/msgpack.encode` preserves JS object
 * insertion order; `rmp_serde::to_vec_named` writes fields in Rust struct
 * DECLARATION order (see the fixture's `_key_order_note`). The TS builders in
 * `../replication.ts` and the interfaces in `../../types/replication.ts` are
 * ordered to match the Rust `repl_ops.rs` struct field order, so raw byte
 * parity is achievable without a semantic fallback.
 *
 * See `docs/dev-artifacts/roadmap/REPLICATION-CLIENT-SURFACE.md` §4 and task #376.
 */

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { encode } from '@msgpack/msgpack';
import {
  replScope,
  replStream,
  replicationProfile,
  dropReplicationProfile,
  publication,
  dropPublication,
  subscription,
  dropSubscription,
  alterSubscription,
  listPublications,
  listSubscriptions,
  replicationStatus,
} from '../replication.js';

// ── Fixture loader ──────────────────────────────────────────────────

const __dirname = dirname(fileURLToPath(import.meta.url));
const FIXTURE_PATH = resolve(
  __dirname,
  // From src/core/builders/__tests__ up to crates/, then into the sibling
  // shamir-query-builder crate. Five levels of `..`.
  '../../../../..',
  'shamir-query-builder',
  'tests',
  'fixtures',
  'repl_ddl_msgpack.json',
);

/**
 * Load the Rust fixture and return only the 10 op-label → hex-string entries,
 * skipping the documentation keys (`_comment`, `_key_order_note`,
 * `_value_notes`) which are not hex.
 */
function loadFixtureHex(): Record<string, string> {
  const text = readFileSync(FIXTURE_PATH, 'utf8');
  const raw = JSON.parse(text) as Record<string, unknown>;
  const out: Record<string, string> = {};
  for (const [key, value] of Object.entries(raw)) {
    if (key.startsWith('_')) continue; // documentation key
    if (typeof value !== 'string') continue; // non-hex (defensive)
    out[key] = value;
  }
  return out;
}

/** Encode a wire object with `@msgpack/msgpack` and return lowercase hex. */
function encodeToHex(op: unknown): string {
  const bytes = encode(op);
  return Buffer.from(bytes).toString('hex');
}

// ── Canonical inputs (mirror Rust `canonical_ops` 1:1) ──────────────

/**
 * The 10 canonical repl-DDL ops, built through the TS builders with the EXACT
 * same input literals as `canonical_ops()` in
 * `crates/shamir-query-builder/tests/repl_ddl_msgpack.rs`. Wire-byte
 * determinism requires identical input strings.
 *
 * NOTE on `create_subscription`: the Rust builder is positional
 * `subscription(name, upstream, publication, profile)`; the TS builder takes
 * `(name, { upstream, publication, profile })`. The values are identical —
 * only the call shape differs, and the emitted wire object key order is the
 * same (create_subscription, upstream, publication, profile).
 */
function canonicalTsOps(): Array<{ label: string; op: unknown }> {
  return [
    {
      label: 'create_replication_profile',
      op: replicationProfile('cluster', [
        replStream(replScope('app', { repo: 'main' }), 'pull', 'read_only'),
      ]),
    },
    {
      label: 'drop_replication_profile',
      op: dropReplicationProfile('cluster'),
    },
    {
      label: 'create_publication',
      op: publication('pub_all', [replScope('app')]),
    },
    {
      label: 'drop_publication',
      op: dropPublication('pub_all'),
    },
    {
      label: 'create_subscription',
      op: subscription('sub1', {
        upstream: 'leader:9above',
        publication: 'pub_all',
        profile: 'cluster',
      }),
    },
    {
      label: 'drop_subscription',
      op: dropSubscription('sub1'),
    },
    {
      label: 'alter_subscription_set_profile',
      op: alterSubscription('sub1', { set_profile: 'cluster2' }),
    },
    {
      label: 'list_publications',
      op: listPublications(),
    },
    {
      label: 'list_subscriptions',
      op: listSubscriptions(),
    },
    {
      label: 'replication_status',
      op: replicationStatus(),
    },
  ];
}

// ── Parity assertions ───────────────────────────────────────────────

describe('TS↔Rust repl-DDL msgpack byte parity', () => {
  const fixture = loadFixtureHex();

  it('fixture pins exactly 10 ops', () => {
    expect(Object.keys(fixture).sort()).toEqual(
      [
        'alter_subscription_set_profile',
        'create_publication',
        'create_replication_profile',
        'create_subscription',
        'drop_publication',
        'drop_replication_profile',
        'drop_subscription',
        'list_publications',
        'list_subscriptions',
        'replication_status',
      ].sort(),
    );
  });

  // One `it` per op — a byte mismatch reports the exact op label and both
  // hex strings, not a single monolithic failure.
  for (const { label, op } of canonicalTsOps()) {
    it(`byte-identical msgpack for ${label}`, () => {
      const expectedHex = fixture[label];
      expect(expectedHex, `fixture missing entry for \`${label}\``).toBeTypeOf(
        'string',
      );
      const tsHex = encodeToHex(op);
      expect(tsHex).toEqual(expectedHex);
    });
  }
});
