#!/usr/bin/env bash
# bench-vector.sh — single entry point for vector-index benchmarks.
#
# Runs BOTH vector tools and assembles a report skeleton under
# docs/benchmarks/vector/<date>-baseline.md:
#
#   1. V0.3 criterion latency bench (benches/vector_search.rs) — QUICK by
#      default (or SMOKE via BENCH_SMOKE=1; 1M rung via BENCH_VECTOR_1M=1).
#   2. V0.4 recall/RSS report (examples/vector_report.rs) — recall@1/@10,
#      build time, peak RSS over the SAME clustered dataset + HNSW params.
#
# Both run against an ISOLATED target dir (CLAUDE.md mandate: benches must
# not invalidate the test/clippy incremental cache in target/). The literal
# below mirrors the workspace convention.
#
# Usage:
#   ./scripts/bench-vector.sh                 # criterion (QUICK) + report
#   BENCH_SMOKE=1 ./scripts/bench-vector.sh   # criterion SMOKE + report (CI)
#   BENCH_VECTOR_1M=1 ./scripts/bench-vector.sh  # + the 1M rung (long)
#   VR_N=50000 ./scripts/bench-vector.sh      # custom report n
#
# Env knobs (all optional):
#   BENCH_SMOKE=1        — criterion SMOKE tier (sample=3, ~5s/cell)
#   BENCH_VECTOR_1M=1    — enable the 1M rung in BOTH tools
#   VR_N / VR_DIMS / VR_QUERIES / VR_SEED / VR_K_CLUSTERS / VR_SIGMA
#                        — forwarded to vector_report (see its --help header)
set -euo pipefail

# Cargo PATH — non-login shells (CI, bash -c) may not have it.
[ -r "$HOME/.cargo/env" ] && . "$HOME/.cargo/env"
export PATH="$HOME/.cargo/bin:$PATH"

cd "$(dirname "$0")/.."

# Isolated target dir — benches MUST NOT clobber the workspace target/
# (invalidates the test/clippy incremental cache). Forward-slash form so
# both Git-Bash on Windows and bash on Linux/WSL accept it.
export CARGO_TARGET_DIR="D:/dev/rust/.cargo-target-bench"
mkdir -p "$CARGO_TARGET_DIR"

DATE="$(date -u +%Y-%m-%d)"
SUFFIX=""
[ "${BENCH_SMOKE:-0}" = "1" ] && SUFFIX="${SUFFIX}-smoke"
[ "${BENCH_VECTOR_1M:-0}" = "1" ] && SUFFIX="${SUFFIX}-1m"
[ -z "$SUFFIX" ] && SUFFIX="-quick"
REPORT="docs/benchmarks/vector/${DATE}${SUFFIX}-baseline.md"

echo "=== bench-vector.sh ==="
echo "  CARGO_TARGET_DIR = $CARGO_TARGET_DIR"
echo "  tier             = ${SUFFIX#-}"
echo "  report           = $REPORT"
echo "  BENCH_SMOKE      = ${BENCH_SMOKE:-0}"
echo "  BENCH_VECTOR_1M  = ${BENCH_VECTOR_1M:-0}"
date -u +%H:%M:%S

mkdir -p docs/benchmarks/vector

# ── 1. criterion latency bench (V0.3) ──────────────────────────────
# The bench reads BENCH_SMOKE / BENCH_VECTOR_1M itself (via
# shamir_bench_utils::tune + the ladder() helper), so we just forward
# the env and let it run.
echo "--- criterion: vector_search ---"
cargo bench -p shamir-engine --bench vector_search 2>&1 | tee "$REPORT.criterion.log"

# ── 2. recall + RSS report (V0.4) ──────────────────────────────────
# NOTE: run the built binary DIRECTLY — the perimeter cargo-runner guard
# (.cargo/config.toml) refuses `cargo run` (it only lets through nextest
# and `cargo bench --bench`), so `cargo run --example` would be blocked.
# Build with cargo, then exec the artefact ourselves. Also bridge the
# 1M flag: the example reads VR_N_1M, the script's knob is BENCH_VECTOR_1M.
echo "--- example: vector_report ---"
[ "${BENCH_VECTOR_1M:-0}" = "1" ] && export VR_N_1M=1
cargo build --release -p shamir-engine --example vector_report
"$CARGO_TARGET_DIR/release/examples/vector_report" 2>&1 \
  | tee "$REPORT.report.log"

# ── 3. assemble the report skeleton ────────────────────────────────
{
  echo "# Vector benchmark — ${DATE} (${SUFFIX#-})"
  echo
  echo "Generated by \`scripts/bench-vector.sh\`. Reproducibility key + raw"
  echo "tables below — paste the relevant block into a dated baseline file."
  echo
  echo "<!-- criterion raw log: $REPORT.criterion.log -->"
  echo "<!-- report raw log:    $REPORT.report.log    -->"
  echo
  echo "## Recall / RSS (vector_report)"
  echo
  echo '```markdown'
  # The example prints a ready-to-paste markdown block; lift it verbatim.
  grep -A 1000 '^<!-- vector_report' "$REPORT.report.log" || true
  echo '```'
  echo
  echo "## Latency (criterion, vector_search)"
  echo
  echo '```'
  # Criterion's summary lines (the per-bench mean/p99 block) — strip the
  # interactive progress spinner noise, keep the results table.
  grep -E '^(Benchmarking|running|vector_search|time:|change:|Performance|.*mean|.*±|.*p99|Found)' \
    "$REPORT.criterion.log" || true
  echo '```'
} > "$REPORT"

echo
echo "=== done → $REPORT ==="
